"""create table

Revision ID: 1932fa282b57
Revises: 46ddeba54f69
Create Date: 2023-03-22 14:09:41.704230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1932fa282b57'
down_revision = '46ddeba54f69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
