"""create table

Revision ID: 2b25b74833e1
Revises: 2df0fd049985
Create Date: 2023-03-22 14:43:02.308409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b25b74833e1'
down_revision = '2df0fd049985'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
