"""create table

Revision ID: 2df0fd049985
Revises: 1932fa282b57
Create Date: 2023-03-22 14:31:47.670231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df0fd049985'
down_revision = '1932fa282b57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
