"""add reports 3

Revision ID: 326426fe4db7
Revises: bb354930d75c
Create Date: 2023-03-08 16:04:12.985038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326426fe4db7'
down_revision = 'bb354930d75c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('deta', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('prise', sa.Float(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('marriage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
