"""create table

Revision ID: 335967047ba0
Revises: 2b25b74833e1
Create Date: 2023-03-22 14:47:45.020811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335967047ba0'
down_revision = '2b25b74833e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
