"""debag reports

Revision ID: 46ddeba54f69
Revises: 326426fe4db7
Create Date: 2023-03-08 23:14:20.235963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ddeba54f69'
down_revision = '326426fe4db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###
