"""prod_category

Revision ID: 504a917a8ba7
Revises: 0044d01fe154
Create Date: 2023-03-03 15:21:44.182480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504a917a8ba7'
down_revision = '0044d01fe154'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_user_id'), 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_user_id'), 'users', type_='unique')
    # ### end Alembic commands ###
