"""add reports

Revision ID: b0f9a0565247
Revises: 533a0c6b47c7
Create Date: 2023-03-08 16:00:27.393200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f9a0565247'
down_revision = '533a0c6b47c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
