"""add reports 2

Revision ID: bb354930d75c
Revises: b0f9a0565247
Create Date: 2023-03-08 16:01:20.227334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb354930d75c'
down_revision = 'b0f9a0565247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
