version: "3.9"

services:
  postgres:
    container_name: ppostgres.postgres
    image: "postgres:15-alpine"
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:8765:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ubnfhf
      POSTGRES_DB: my_db
    volumes:
      - "ppostgres.postgres.data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: miha@mial.ru
      PGADMIN_DEFAULT_PASSWORD: ubnfhf
    ports:
        - "5050:80"

volumes:
  ppostgres.postgres.data: {}